#!/usr/bin/env node
/**
 * add-srcset.js
 *
 * Updates all <source> elements in <picture> wrappers to use responsive srcset
 * with 480w, 960w, and full-size entries, plus a sizes attribute.
 *
 * Adds the corresponding _480w and _960w WebP imports next to each existing
 * WebP import. Skips images whose baseName is not in srcset-widths.json
 * (i.e. small-rendered images that were intentionally excluded).
 *
 * Usage: node scripts/add-srcset.js [--dry-run]
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DRY_RUN = process.argv.includes('--dry-run');

const widthMap = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'srcset-widths.json'), 'utf8')
);

// basename → set of varNames that import it (built per-file)
// sized attr for all images
const SIZES = '(max-width: 1024px) 100vw, 50vw';

const FILES = [
  'client/src/components/Hero.tsx',
  'client/src/pages/AIFeatures.tsx',
  'client/src/components/ComplianceSection.tsx',
  'client/src/components/RCMSection.tsx',
  'client/src/pages/Management.tsx',
  'client/src/pages/RCM.tsx',
  'client/src/pages/CardiologySpecialty.tsx',
  'client/src/pages/DermatologySpecialty.tsx',
  'client/src/pages/ClickLessCareMore.tsx',
  'client/src/pages/Contact.tsx',
  'client/src/pages/EHR.tsx',
  'client/src/pages/FamilyMedicineSpecialty.tsx',
  'client/src/pages/OBGYNSpecialty.tsx',
  'client/src/pages/OurMission.tsx',
  'client/src/pages/PediatricsSpecialty.tsx',
  'client/src/pages/Support.tsx',
  'client/src/pages/UrologySpecialty.tsx',
];

function processFile(filePath) {
  const fullPath = path.join(ROOT, filePath);
  let content = fs.readFileSync(fullPath, 'utf8');
  const original = content;

  // ── Step 1: collect WebP imports from @assets/generated_images ──
  // Pattern: import VARNAME from "@assets/generated_images/BASENAME.webp";
  // We only want the main WebP (not the _480w or _960w variants already added)
  const webpImportRe = /^(import (\w+) from "@assets\/generated_images\/(?!.*_(?:480|960)w\.webp)(.+?)\.webp";)$/gm;
  const webpVars = new Map(); // varName → { baseName, fullImportLine }
  let m;
  while ((m = webpImportRe.exec(content)) !== null) {
    webpVars.set(m[2], { baseName: m[3], fullImportLine: m[1] });
  }

  if (webpVars.size === 0) {
    console.log(`  SKIP (no webp imports): ${filePath}`);
    return;
  }

  // ── Step 2: add _480w and _960w imports after each WebP import ──
  for (const [varName, { baseName, fullImportLine }] of webpVars) {
    // Only add if the baseName has srcset files generated
    if (!widthMap[baseName]) continue;

    const import480 = `import ${varName}480 from "@assets/generated_images/${baseName}_480w.webp";`;
    const import960 = `import ${varName}960 from "@assets/generated_images/${baseName}_960w.webp";`;

    if (!content.includes(import480)) {
      content = content.replace(fullImportLine, `${fullImportLine}\n${import480}\n${import960}`);
    }
  }

  // ── Step 3: update <source srcSet={xWebp} type="image/webp" /> ──
  // Regex matches exactly the pattern generated by wrap-picture.js / pilot edits
  const sourceRe = /<source srcSet=\{(\w+)\} type="image\/webp" \/>/g;

  content = content.replace(sourceRe, (match, varName) => {
    const info = webpVars.get(varName);
    if (!info) {
      // Variable not in our WebP imports map — leave unchanged
      return match;
    }
    const { baseName } = info;
    if (!widthMap[baseName]) {
      // No srcset files for this image (small-rendered) — leave unchanged
      return match;
    }

    const naturalWidth = widthMap[baseName];
    const v480 = `${varName}480`;
    const v960 = `${varName}960`;

    return `<source srcSet={\`\${${v480}} 480w, \${${v960}} 960w, \${${varName}} ${naturalWidth}w\`} sizes="${SIZES}" type="image/webp" />`;
  });

  if (content === original) {
    console.log(`  NO CHANGE: ${filePath}`);
    return;
  }

  if (DRY_RUN) {
    console.log(`  [DRY-RUN] ${filePath}`);
    const lines = content.split('\n');
    lines.forEach((line, i) => {
      if ((line.includes('srcSet={`') || line.includes('_480w') || line.includes('_960w')) && !line.includes('//')){
        console.log(`    L${i+1}: ${line.trim()}`);
      }
    });
  } else {
    fs.writeFileSync(fullPath, content);
    const count = (content.match(/<source srcSet=\{`/g) || []).length;
    console.log(`  UPDATED: ${filePath} (${count} responsive sources)`);
  }
}

console.log(`\nadd-srcset.js${DRY_RUN ? ' [DRY-RUN]' : ''}\n`);
for (const f of FILES) {
  try {
    processFile(f);
  } catch (err) {
    console.error(`  ERROR in ${f}: ${err.message}`);
  }
}
console.log('\nDone.');
